name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [13.x]

    steps:
    - uses: actions/checkout@v2
    - name: Git pull
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: cd /www/static/mango.moe; git pull;
        host: ${{ secrets.HOST }}
        username: root
        password: ${{ secrets.PASSWORD }}
